### ISSUE TITLE
hmm..fixed now

### ISSUE THREAD

**Issue by jsbueno** [jima80525/ctypes_example#3]
https://github.com/jima80525/ctypes_example/blob/07e89a10b5b933212932473f6f7f47c38e2a01d0/tutorial2/testWrappedPoint.py#L21

Good to see you fixed the `__init__` for your point wrapper. I was reading the post, and upon finding the attribution `self = get_point()` here, I came here to file the bug at once.  :-)  

`self` is just a normal variable inside a method, and attributing to it will just make it point to another object, not "self" anymore.

**Comment by jima80525** [comment]
Yes.   Thanks!  I'll admit that a different contributor fixed that for me the day the article was published.
