### ISSUE TITLE
Change MapGetter to use import hooks

### ISSUE THREAD

**Issue by jsbueno** [jima80525/ctypes_example#5]
Currently, MapGetter naively replaces the builtin `__import__` inside the `with` block. The existing import hooks seems to offer ways to make that in a cleaner way.

**Comment by jima80525** [comment]
I'm going to confess that you lost me here.  Where in the code are you talking about?

**Comment by jsbueno** [comment]
this issue was open on the wrong project. hah..too many github tabs!  This wa sto be a reminder for myself in jsbueno/extradict.
